### ISSUE TITLE
Add 'check for update' (manually and automatic) function

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/unity#130]
Have the client check for updates, if a new update is available notify the user and provide download linux.

We can probably ignore this on mobile devices.

**Comment by bdlukaa** [comment]
We can make this work using the [upgrader](https://pub.dev/packages/upgrader) package. It works in the following way:

1. We store a versioning file on the project (`appcast.xml`) which looks something like:
   https://pub.dev/packages/upgrader#appcast
  ```xml
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
    <channel>
        <title>Bluecherry DVR - Appcast</title>
        <item>
            <title>Version 1.15.0</title>
            <description>Minor updates and improvements.</description>
            <pubDate>Sun, 30 Dec 2018 12:00:00 +0000</pubDate>
            <enclosure url="https://play.google.com/store/apps/details?id=com.moonwink.treasury" sparkle:version="1.15.0" sparkle:os="android" />
        </item>
    </channel>
</rss>
  ```
2. On every app launch, the package will check for any version updates and prompt the user to install it. We can also add a section on the `Settings` screen with options to upgrade

Obviously, some updates will be necessary to update the app directly from itself.
  * On Android and iOS, the version info comes from the store itself, so no extra steps are required;
  * On Windows, a `msi` installer can be used for a silent update. Since we currently make use of a Inno Setup Executable, they provide [documentation for updates](https://jrsoftware.org/ishelp/index.php?topic=technotes);
  * On Linux, *investigation needed*
