### ISSUE TITLE
Clicking on "open in a new window" on the main view does nothing:

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/unity#76]
Clicking on "open in a new window" on the main view does nothing:

![open-new-window-gMmW8naZl8](https://user-images.githubusercontent.com/1145561/222535232-0397694d-ac53-4c1d-945d-80d9a0e7fb6c.png)

_Originally posted by @guillebot in https://github.com/bluecherrydvr/unity/discussions/74#discussioncomment-5182662_

**Comment by bdlukaa** [comment]
This is a regression. This is probably related to the single instance of the app? If that is the case, we may want to switch to the `View` implementation ([Learn more](https://www.youtube.com/watch?v=vtB-teu57vw&ab_channel=Flutter))

**Comment by bdlukaa** [comment]
This is kind of blocked by the way we store data to the storage. Currently, we make use of [`hive`](https://pub.dev/packages/hive), which only allows one file per session. When a new window is opened, the app doesn't initialize because it gets stuck trying to read the locked file. This was the reason we didn't allow multiple app instances.

To fix this issue, we should first find a storage system that allows multiple instances, or create our own (shouldn't be hard)

**Comment by alexmercerind** [comment]
I use my own solution (if you wish to): https://github.com/alexmercerind/safe_local_storage.

Simple JSON based storage with atomic, consistent & roll-back handling.

**Comment by alexmercerind** [comment]
No platform channel.
